import { HttpClient, HttpHeaders } from "@angular/common/http";
//const serverUrl = "http://102.219.178.102:3031/";
const serverUrl = "http://sayara.tn:3032/";
const arrayCategories = [{ category: 'VEHICLES' }, { category: 'IMMOBILIER' },
{ category: 'MULTIMEDIA' }, { category: 'MAISON' }, { category: 'LOISIRS' },
{ category: 'SERVICES' }, { category: 'MATERIEL PROFESSIONNEL' }, { category: 'EMPLOI' }
  , { category: 'VACANCES' }, { category: 'MODE' }];
const arraysecurityEquipment = [{ equipement: 'Airbags frontaux',checked:false },
{ equipement: 'Airbags latéraux ',checked:false },
{ equipement: 'Airbags rideaux',checked:false },
{ equipement: 'Alarme anti-intrusion',checked:false },
{ equipement: 'Anti-patinage',checked:false },
{ equipement: 'Fixations ISOFIX',checked:false },
{ equipement: 'Pneumatiques runflat',checked:false },
{ equipement: 'Radiateur tropicalisé',checked:false },
{ equipement: 'Anti-démarrage électronique',checked:false },
{ equipement: 'Contrôle de pression des pneus',checked:false },];

const arrayOutsideEquipment = [{ equipement: 'Antibrouillards',checked:false },
{ equipement: 'Détecteur de luminosité',checked:false },
{ equipement: 'Détecteur de pluie',checked:false },
{ equipement: 'Fermeture centralisée',checked:false },
{ equipement: 'Feux à LED',checked:false },
{ equipement: 'Jantes en alliage',checked:false },
{ equipement: 'Lave Phares',checked:false },
{ equipement: 'Peinture métallisée',checked:false },
{ equipement: 'Phares au xénon',checked:false },
{ equipement: 'Radar de recul',checked:false },
{ equipement: 'Toit ouvrant',checked:false },
{ equipement: 'Toit panoramique',checked:false },
{ equipement: 'Vitres teintées',checked:false },
{ equipement: 'Rétroviseurs électriques',checked:false },
{ equipement: 'Rétroviseurs rabattables',checked:false },]

const arrayInsideEquipment = [{ equipement: 'Accoudoir avant' ,checked:false},
{ equipement: 'Accoudoir arrière',checked: false },
{ equipement: 'Autoradio' ,checked:false},
{ equipement: 'Autoradio CD' ,checked:false},
{ equipement: 'Autoradio CD/Mp3' ,checked:false},
{ equipement: 'Bluetooth' ,checked:false},
{ equipement: 'Boîte à gants réfrigérée' ,checked:false},
{ equipement: 'Bouton Start / Stop' ,checked:false},
{ equipement: 'Caméra de recul' ,checked:false},
{ equipement: 'Chargeur CD' ,checked:false},
{ equipement: 'Climatisation' ,checked:false},
{ equipement: 'Climatronic' ,checked:false},
{ equipement: 'Direction assistée' ,checked:false},
{ equipement: 'GPS' ,checked:false},
{ equipement: 'Ordinateur de bord' ,checked:false},
{ equipement: 'Palettes au volant' ,checked:false},
{ equipement: 'Régulateur de vitesse' ,checked:false},
{ equipement: 'Sellerie en cuir' ,checked:false},
{ equipement: 'Sièges électriques' ,checked:false},
{ equipement: 'Sièges chauffants' ,checked:false},
{ equipement: 'Vitres électriques' ,checked:false},
{ equipement: 'Vitres teintées' ,checked:false},
{ equipement: 'Volant multi-fonctions' ,checked:false},
{ equipement: 'appuis têtes arrières' ,checked:false},
{ equipement: 'Sièges réglables en hauteur' ,checked:false},
{ equipement: 'Volant/levier de vitesse en cuir' ,checked:false},
{ equipement: 'Connectivité Aux, usb, iPod' ,checked:false},
{ equipement: 'Volant réglable hauteur/profondeur' ,checked:false }]

const arrayCategoryCar = [{ category: 'Luxury'}, { category: 'Sports'},
{ category: 'Vintage' }, { category: 'Excutive' }, { category: 'Economy' },]




const arrayBrand = [
  { brand: "Acura",model:['MDX', 'NSX', 'RL', 'RSX', 'TL' ,'TSX'] },
  { brand: "Aixam", model:['City','crossline','Roadline','Scouty R']},
  { brand: "Alfa Romeo" , model:[ '145', '146', '147', '149','155','156','159','164','166','33','75','8C','90','Alfasud','Alfetta','Autre','Brera','Crosswagon', 
  'Giulia','Giulietta','GT','GTV','Junior','Mito','RZ/SZ','Spider','Sprint','Stelvio']},
  { brand: "Alpina" , model:[]},
  { brand: "Aston Martin" , model:[]},
  { brand: "Audi" , model:[]},
  { brand: "BAIC YX" , model:[]},
  { brand: "Bentley" , model:[]},
  { brand: "BMW" , model:[]},
  { brand: "Bugatti" , model:[]},
  { brand: "Buick" , model:[]},
  { brand: "BYD" , model:[]},
  { brand: "Cadillac" , model:[]},
  { brand: "Changan" , model:[]},
  { brand: "Chery" , model:[]},
  { brand: "Chevrolet" , model:[]},
  { brand: "Chrysler" , model:[]},
  { brand: "Citroën" , model:[]},
  { brand: "Dacia" , model:[]},
  { brand: "Daewoo" , model:[]},
  { brand: "Daihatsu" , model:[]},
  { brand: "DFSK" , model:[]},
  { brand: "Dodge" , model:[]},
  { brand: "Dongfeng" , model:[]},
  { brand: "DS" , model:[]},
  { brand: "Faw" , model:[]},
  { brand: "Ferrari" , model:[]},
  { brand: "Fiat" , model:[]},
  { brand: "Foday" , model:[]},
  { brand: "Ford" , model:[]},
  { brand: "Foton" , model:[]},
  { brand: "Geely" , model:[]},
  { brand: "Genesis" , model:[]},
  { brand: "GMC" , model:[]},
  { brand: "Great Wall" , model:[]},
  { brand: "Haval" , model:[]},
  { brand: "Honda" , model:[]},
  { brand: "Huanghai" , model:[]},
  { brand: "Hummer" , model:[]},
  { brand: "Hyundai" , model:[]},
  { brand: "Infiniti" , model:[]},
  { brand: "Isuzu" , model:[]},
  { brand: "Iveco" , model:[]},
  { brand: "Jaguar" , model:[]},
  { brand: "Jeep" , model:[]},
  { brand: "Kawazaki" , model:[]},
  { brand: "KIA" , model:[]},
  { brand: "Lada" , model:[]},
  { brand: "Lamborghini" , model:[]},
  { brand: "Lancia" , model:[]},
  { brand: "Land Rover" , model:[]},
  { brand: "Lexus" , model:[]},
  { brand: "Lincoln" , model:[]},
  { brand: "Lotus" , model:[]},
  { brand: "Mahindra" , model:[]},
  { brand: "Maserati" , model:[]},
  { brand: "Maybach" , model:[]},
  { brand: "Mazda" , model:[]},
  { brand: "Mercedes-Benz" , model:[]},
  { brand: "MG" , model:[]},
  { brand: "Mini" , model:[]},
  { brand: "Mitsubishi" , model:[]},
  { brand: "Morgan" , model:[]},
  { brand: "Nissan" , model:[]},
  { brand: "Oldsmobile" , model:[]},
  { brand: "Opel" , model:[]},
  { brand: "Peugeot" , model:[]},
  { brand: "Piaggio" , model:[]},
  { brand: "Pontiac" , model:[]},
  { brand: "Porsche" , model:[]},
  { brand: "Renault" , model:[]},
  { brand: "Rolls Royce" , model:[]},
  { brand: "Rover" , model:[]},
  { brand: "Saab" , model:[]},
  { brand: "Seat" , model:[]},
  { brand: "Simca" , model:[]},
  { brand: "Skoda" , model:[]},
  { brand: "Smart" , model:[]},
  { brand: "Soueast" , model:[]},
  { brand: "Ssangyong" , model:[]},
  { brand: "Subaru" , model:[]},
  { brand: "Suzuki" , model:[]},
  { brand: "Talbot" , model:[]},
  { brand: "Tata" , model:[]},
  { brand: "Toyota" , model:[]},
  { brand: "Trabant" , model:[]},
  { brand: "Triumph" , model:[]},
  { brand: "TVR" , model:[]},
  { brand: "Volkswagen" , model:[]},
  { brand: "Volvo" , model:[]},
  { brand: "Wallyscar" , model:[]},
]

const headers = new HttpHeaders({
  "Content-Type": "application/json",
  Authorization: "Bearer " + localStorage.getItem("accessToken"),
});
export { serverUrl, headers, arrayCategories, arrayInsideEquipment, arrayOutsideEquipment,
   arraysecurityEquipment, arrayCategoryCar,arrayBrand }