import { HttpClient, HttpHeaders } from "@angular/common/http";
const serverUrl = "http://102.219.178.102:3031/";
const arrayCategories = [{ category: 'VEHICLES' }, { category: 'IMMOBILIER' },
{ category: 'MULTIMEDIA' }, { category: 'MAISON' }, { category: 'LOISIRS' },
{ category: 'SERVICES' }, { category: 'MATERIEL PROFESSIONNEL' }, { category: 'EMPLOI' }
  , { category: 'VACANCES' }, { category: 'MODE' }];
const arraysecurityEquipment = [{ equipement: 'Airbags frontaux' },
{ equipement: 'Airbags latéraux ' },
{ equipement: 'Airbags rideaux' },
{ equipement: 'Alarme anti-intrusion' },
{ equipement: 'Anti-patinage' },
{ equipement: 'Fixations ISOFIX' },
{ equipement: 'Pneumatiques runflat' },
{ equipement: 'Radiateur tropicalisé' },
{ equipement: 'Anti-démarrage électronique' },
{ equipement: 'Contrôle de pression des pneus' },];

const arrayOutsideEquipment = [{ equipement: 'Antibrouillards' },
{ equipement: 'Détecteur de luminosité' },
{ equipement: 'Détecteur de pluie' },
{ equipement: 'Fermeture centralisée' },
{ equipement: 'Feux à LED' },
{ equipement: 'Jantes en alliage' },
{ equipement: 'Lave Phares' },
{ equipement: 'Peinture métallisée' },
{ equipement: 'Phares au xénon' },
{ equipement: 'Radar de recul' },
{ equipement: 'Toit ouvrant' },
{ equipement: 'Toit panoramique' },
{ equipement: 'Vitres teintées' },
{ equipement: 'Rétroviseurs électriques' },
{ equipement: 'Rétroviseurs rabattables' },]

const arrayInsideEquipment = [{ equipement: 'Accoudoir avant' },
{ equipement: 'Accoudoir arrière' },
{ equipement: 'Autoradio' },
{ equipement: 'Autoradio CD' },
{ equipement: 'Autoradio CD/Mp3' },
{ equipement: 'Bluetooth' },
{ equipement: 'Boîte à gants réfrigérée' },
{ equipement: 'Bouton Start / Stop' },
{ equipement: 'Caméra de recul' },
{ equipement: 'Chargeur CD' },
{ equipement: 'Climatisation' },
{ equipement: 'Climatronic' },
{ equipement: 'Direction assistée' },
{ equipement: 'GPS' },
{ equipement: 'Ordinateur de bord' },
{ equipement: 'Palettes au volant' },
{ equipement: 'Régulateur de vitesse' },
{ equipement: 'Sellerie en cuir' },
{ equipement: 'Sièges électriques' },
{ equipement: 'Sièges chauffants' },
{ equipement: 'Vitres électriques' },
{ equipement: 'Vitres teintées' },
{ equipement: 'Volant multi-fonctions' },
{ equipement: 'appuis têtes arrières' },
{ equipement: 'Sièges réglables en hauteur' },
{ equipement: 'Volant/levier de vitesse en cuir' },
{ equipement: 'Connectivité Aux, usb, iPod' },
{ equipement: 'Volant réglable hauteur/profondeur' }]

const arrayCategoryCar = [{ category: 'Luxury' }, { category: 'Sports' },
{ category: 'Vintage' }, { category: 'Excutive' }, { category: 'Economy' },]




const arrayBrand = [
  { brand: "Acura",model:['MDX', 'NSX', 'RL', 'RSX', 'TL' ,'TSX'] },
  { brand: "Aixam", model:['City','crossline','Roadline','Scouty R']},
  { brand: "Alfa Romeo" , model:[ '145', '146', '147', '149','155','156','159','164','166','33','75','8C','90','Alfasud','Alfetta','Autre','Brera','Crosswagon', 
  'Giulia','Giulietta','GT','GTV','Junior','Mito','RZ/SZ','Spider','Sprint','Stelvio']},
  { brand: "Alpina" , model:[]},
  { brand: "Aston Martin" , model:[]},
  { brand: "Audi" , model:[]},
  { brand: "BAIC YX" , model:[]},
  { brand: "Bentley" , model:[]},
  { brand: "BMW" , model:[]},
  { brand: "Bugatti" , model:[]},
  { brand: "Buick" , model:[]},
  { brand: "BYD" , model:[]},
  { brand: "Cadillac" , model:[]},
  { brand: "Changan" , model:[]},
  { brand: "Chery" , model:[]},
  { brand: "Chevrolet" , model:[]},
  { brand: "Chrysler" , model:[]},
  { brand: "Citroën" , model:[]},
  { brand: "Dacia" , model:[]},
  { brand: "Daewoo" , model:[]},
  { brand: "Daihatsu" , model:[]},
  { brand: "DFSK" , model:[]},
  { brand: "Dodge" , model:[]},
  { brand: "Dongfeng" , model:[]},
  { brand: "DS" , model:[]},
  { brand: "Faw" , model:[]},
  { brand: "Ferrari" , model:[]},
  { brand: "Fiat" , model:[]},
  { brand: "Foday" , model:[]},
  { brand: "Ford" , model:[]},
  { brand: "Foton" , model:[]},
  { brand: "Geely" , model:[]},
  { brand: "Genesis" , model:[]},
  { brand: "GMC" , model:[]},
  { brand: "Great Wall" , model:[]},
  { brand: "Haval" , model:[]},
  { brand: "Honda" , model:[]},
  { brand: "Huanghai" , model:[]},
  { brand: "Hummer" , model:[]},
  { brand: "Hyundai" , model:[]},
  { brand: "Infiniti" , model:[]},
  { brand: "Isuzu" , model:[]},
  { brand: "Iveco" , model:[]},
  { brand: "Jaguar" , model:[]},
  { brand: "Jeep" , model:[]},
  { brand: "Kawazaki" , model:[]},
  { brand: "KIA" , model:[]},
  { brand: "Lada" , model:[]},
  { brand: "Lamborghini" , model:[]},
  { brand: "Lancia" , model:[]},
  { brand: "Land Rover" , model:[]},
  { brand: "Lexus" , model:[]},
  { brand: "Lincoln" , model:[]},
  { brand: "Lotus" , model:[]},
  { brand: "Mahindra" , model:[]},
  { brand: "Maserati" , model:[]},
  { brand: "Maybach" , model:[]},
  { brand: "Mazda" , model:[]},
  { brand: "Mercedes-Benz" , model:[]},
  { brand: "MG" , model:[]},
  { brand: "Mini" , model:[]},
  { brand: "Mitsubishi" , model:[]},
  { brand: "Morgan" , model:[]},
  { brand: "Nissan" , model:[]},
  { brand: "Oldsmobile" , model:[]},
  { brand: "Opel" , model:[]},
  { brand: "Peugeot" , model:[]},
  { brand: "Piaggio" , model:[]},
  { brand: "Pontiac" , model:[]},
  { brand: "Porsche" , model:[]},
  { brand: "Renault" , model:[]},
  { brand: "Rolls Royce" , model:[]},
  { brand: "Rover" , model:[]},
  { brand: "Saab" , model:[]},
  { brand: "Seat" , model:[]},
  { brand: "Simca" , model:[]},
  { brand: "Skoda" , model:[]},
  { brand: "Smart" , model:[]},
  { brand: "Soueast" , model:[]},
  { brand: "Ssangyong" , model:[]},
  { brand: "Subaru" , model:[]},
  { brand: "Suzuki" , model:[]},
  { brand: "Talbot" , model:[]},
  { brand: "Tata" , model:[]},
  { brand: "Toyota" , model:[]},
  { brand: "Trabant" , model:[]},
  { brand: "Triumph" , model:[]},
  { brand: "TVR" , model:[]},
  { brand: "Volkswagen" , model:[]},
  { brand: "Volvo" , model:[]},
  { brand: "Wallyscar" , model:[]},
]

const headers = new HttpHeaders({
  "Content-Type": "application/json",
  Authorization: "Bearer " + localStorage.getItem("access_token"),
});
export { serverUrl, headers, arrayCategories, arrayInsideEquipment, arrayOutsideEquipment,
   arraysecurityEquipment, arrayCategoryCar,arrayBrand }